version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:15"
      timezone: Europe/London
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: Europe/London
    open-pull-requests-limit: 3
